freebsd_task:
  name: FreeBSD 12.1
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f; pkg install -y cmake fusefs-libs pkgconf python3 py36-pip
    - kldload fuse
    - kldstat
    - python3 -m pip install --user pytest
  test_script:
    - cmake -S . -B build
    - cmake --build build
    - make -C build test

macos_catalina_task:
  name: macOS Catalina
  osx_instance:
    image: catalina-base
  install_script:
    - brew install --cask osxfuse
    - brew install cmake
  test_script:
    - cmake -S . -B build
    - cmake --build build
    - make -C build test

macos_bigsur_task:
  name: macOS Big Sur
  osx_instance:
    image: big-sur-base
  install_script:
    - brew update-reset
    - brew upgrade
    - brew install --cask osxfuse
    - brew install cmake python3
    - python3 -m pip install --user pytest
  test_script:
    - cmake -S . -B build
    - cmake --build build
    - make -C build test
