language: c
compiler:
  - clang
  - gcc

dist: bionic

addons:
  apt:
    packages:
      - libfuse-dev fuse python-pytest

script:
  - mkdir build
  - cmake -S . -B build
  - cmake --build build
  - make -C build test
